# Generated by Django 5.1.3 on 2024-11-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
