# Generated by Django 5.1.3 on 2024-11-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slambooks',
            fields=[
                ('slamid', models.AutoField(primary_key=True, serialize=False)),
                ('slamtitle', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
