# Generated by Django 5.1.3 on 2024-11-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_slambooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('MCQ', 'Mcq'), ('MSQ', 'Msq'), ('Text_One', 'Text One'), ('Text_multi', 'Text Multi'), ('IMAGE', 'Image'), ('DATE', 'Date'), ('Bottle', 'Bottle')], max_length=10)),
                ('max_selection', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.slambooks')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Options',
            fields=[
                ('optionid', models.AutoField(primary_key=True, serialize=False)),
                ('optiontext', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.questions')),
            ],
        ),
    ]
