# Generated by Django 5.1.3 on 2024-12-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_url_slambook_alter_questions_type_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
