# Generated by Django 5.1.3 on 2025-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_response_responses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['sequence', 'questionid']},
        ),
        migrations.AddField(
            model_name='questions',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
