# Generated by Django 5.1.3 on 2025-03-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_slambook',
            name='slamid',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='base.slambooks'),
            preserve_default=False,
        ),
    ]
