# Generated by Django 5.1.3 on 2025-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_url_slambook_slamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_answer',
            name='answer_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
